### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by quasiperfect** [NeZaMy/jquery.pinBox#2]
hi

first thanks for your work

if i would want to use the script for a unknown number of elements would this work or you have a better suggestion ?

```
$('.pinBox').each( function( index, el ) {
    $(el).pinBox({
        Top : $(el).data('pin-top'),
        Container : $(el).data('pin-container'),
        ZIndex : $(el).data('pin-index'),
        MinWidth : $(el).data('pin-breakpoint')
    });
});
```

**Comment by nezamy** [comment]
it's working for a unknown number of elements
just do this

``` js
$('.pinBox').pinBox({
    Top : $('.pinBox').data('pin-top'),
    Container : $('.pinBox').data('pin-container'),
    ZIndex : $('.pinBox').data('pin-index'),
    MinWidth : $('.pinBox').data('pin-breakpoint')
});
```

**if every element have special options your code will work better .**

**Comment by quasiperfect** [comment]
@NeZaMy thanks for responding. i will implement you script in my next project
